# Auto-generated by airis-workspace from workspace.yaml
# DO NOT EDIT - Regenerate with: airis generate

project := "airis-mcp-gateway"
workspace := "workspace"

# Default recipe (show help)
default:
    @just --list

# ============================================
# Docker Management
# ============================================

# Start all services
up:
    @echo "🚀 Starting Docker services..."
    docker compose up -d
    @echo "✅ Services started"

# Rebuild (images + containers)
rebuild:
    @echo "🔁 Rebuilding Docker services..."
    docker compose up -d --build
    @echo "✅ Services rebuilt"

# Build container images
build:
    @echo "🏗️ Building Docker images..."
    docker compose build
    @echo "✅ Images built"

# Stop all services
down:
    docker compose down --remove-orphans

# Install dependencies (in Docker)
install:
    @echo "📦 Installing dependencies in Docker..."
    docker compose exec workspace pnpm install
    @echo "✅ Dependencies installed"

# Enter workspace shell
workspace:
    docker compose exec -it workspace sh

# Show logs
logs:
    docker compose logs -f

# Show container status
ps:
    docker compose ps

# Clean artifacts
clean:
    rm -rf ./node_modules ./dist ./.next ./build ./target
    find . -name ".DS_Store" -delete 2>/dev/null || true

# ============================================
# TypeScript Library Commands
# ============================================

# Dev TypeScript library
dev-ts name:
    docker compose exec workspace pnpm --filter {{name}} dev

# Build TypeScript library
build-ts name:
    docker compose exec workspace pnpm --filter {{name}} build

# Test TypeScript library
test-ts name:
    docker compose exec workspace pnpm --filter {{name}} test

# ============================================
# Next.js Commands
# ============================================

# Dev Next.js app
dev-next name:
    docker compose exec workspace pnpm --filter {{name}} dev

# Build Next.js app
build-next name:
    docker compose exec workspace pnpm --filter {{name}} build

# Start Next.js production
start-next name:
    docker compose exec workspace pnpm --filter {{name}} start

# ============================================
# Node Service Commands
# ============================================

# Dev Node service
dev-node name:
    docker compose exec workspace pnpm --filter {{name}} dev

# Build Node service
build-node name:
    docker compose exec workspace pnpm --filter {{name}} build

# Start Node service
start-node name:
    docker compose exec workspace pnpm --filter {{name}} start

# ============================================
# Rust Commands (Cargo only, no pnpm)
# ============================================

# Build Rust project
build-rust name:
    cargo build --manifest-path {{name}}/Cargo.toml

# Build Rust release
release-rust name:
    cargo build --release --manifest-path {{name}}/Cargo.toml

# Run Rust project
run-rust name:
    cargo run --manifest-path {{name}}/Cargo.toml

# ============================================
# Docker-First Guards (Prevent Host Pollution)
# ============================================

[private]
guard tool:
    @echo "❌ ERROR: '{{tool}}' は直接使えません"
    @echo ""
    @echo "Docker-Firstアーキテクチャでは、以下を使ってください:"
    @echo "  TypeScript: just dev-ts <name>"
    @echo "  Next.js:    just dev-next <name>"
    @echo "  Node:       just dev-node <name>"
    @echo "  Rust:       just build-rust <name>"
    @echo ""
    @echo "または: just workspace → pnpm <cmd>"
    @exit 1

pnpm *args:
    @just guard pnpm

npm *args:
    @just guard npm

yarn *args:
    @just guard yarn

# ============================================
# Shortcuts (Project-Specific)
# ============================================

# Dev dashboard (nextjs)
dev-dashboard: (dev-next "dashboard")

# Dev api (node)
dev-api: (dev-node "api")
