# Auto-generated by airis init
# DO NOT EDIT - change manifest.toml instead.

project := "airis-mcp-gateway"
manifest := "manifest.toml"
workspace := "workspace"

set shell := ["bash", "-c"]

default:
    @just --list

up:
    @echo "🚀 Starting workspace + infra from manifest.toml..."
    docker compose up -d
    just dev-all

down:
    @echo "🧹 Stopping containers..."
    docker compose down --remove-orphans

workspace:
    docker compose exec -it workspace sh

install:
    docker compose exec workspace pnpm install

logs:
    docker compose logs -f

ps:
    docker compose ps

clean:
    rm -rf ./node_modules ./dist ./.next ./build ./target
    find . -name ".DS_Store" -delete 2>/dev/null || true

dev-all:
	apps="$(airis manifest dev-apps)"
	if [ -z "$$apps" ]; then \
		echo "⚠️  No dev apps defined in manifest.toml (.dev.apps)"; \
		exit 0; \
	fi
	echo "$$apps" | while read -r app; do \
		[ -z "$$app" ] && continue; \
		echo "▶️  docker compose exec workspace pnpm --filter $$app dev"; \
		docker compose exec workspace pnpm --filter "$$app" dev & \
	done
	wait

verify:
	cmds="$(airis manifest rule verify)"
	if [ -z "$$cmds" ]; then \
		echo "⚠️  [rule.verify] is empty in manifest.toml"; \
		exit 1; \
	fi
	echo "$$cmds" | while read -r cmd; do \
		[ -z "$$cmd" ] && continue; \
		echo ">> $$cmd"; \
		eval "$$cmd"; \
	done

ci:
	cmds="$(airis manifest rule ci)"
	if [ -z "$$cmds" ]; then \
		echo "⚠️  [rule.ci] is empty in manifest.toml"; \
		exit 1; \
	fi
	echo "$$cmds" | while read -r cmd; do \
		[ -z "$$cmd" ] && continue; \
		echo ">> $$cmd"; \
		eval "$$cmd"; \
	done

[private]
guard tool:
    @echo "❌ ERROR: '{{tool}}' は直接使えません"
    @echo ""
    @echo "Docker-first ルールに従い、以下を利用してください:"
    @echo "  just dev-all         # manifest.toml のアプリを起動"
    @echo "  just workspace       # workspace コンテナに入る"
    @exit 1

pnpm *args:
    @just guard pnpm

npm *args:
    @just guard npm

yarn *args:
    @just guard yarn
