# airis-mcp-gateway Monorepo Workspaces
#
# Structure:
#   apps/   - デプロイ可能なアプリ (MCP サーバー, CLI, UI)
#   libs/   - 共有ライブラリ
#   tools/  - 開発ツール (measurement など)

packages:
  - "apps/*"
  - "libs/*"
  - "tools/*"
